/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109960-g3153c441e1-20230303"
#endif /* AVUTIL_FFVERSION_H */
